name: 'ERCX Golden Test'
description: 'Run golden tests of ercx library'
inputs:
  infura_api_key:
    description: "The infura API key to be used with forge's fork mainnet mode"
    required: true
  etherscan_api_key:
    description: "The etherscan API key to be used for ABI tests"
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
